accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from accounts.views import signup
from django.contrib.auth import views as auth_views


urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("receipts/", include("receipts.urls")),
    path("", RedirectView.as_view(url=reverse_lazy("home"))),
]

receipts/urls.py
from receipts.views import (
    AccountsCreateView,
    CategoriesCreateView,
    CategoriesListView,
    ReceiptCreateView,
    ReceiptListView,
    AccountsListView,
)


from django.urls import path

urlpatterns = [
    path("", ReceiptListView.as_view(), name="home"),
    path("create/", ReceiptCreateView.as_view(), name="receipt_create"),
    path("accounts/", AccountsListView.as_view(), name="accounts_view"),
    path(
        "accounts/create", AccountsCreateView.as_view(), name="accounts_create"
    ),
    path("categories/", CategoriesListView.as_view(), name="expense_list"),
    path(
        "categories/create",
        CategoriesCreateView.as_view(),
        name="expense_create",
    ),
]

accounts/models.py
from pyexpat import model
from django.db import models
from django.forms import ModelForm

# Create your models here.


class SignUpForm(ModelForm):
    username = models.CharField(max_length=16)

receipts/models.py
from django.db import models

# from django.forms import ModelChoiceField
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL

# Create your models here.
class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        USER_MODEL, related_name="categories", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        USER_MODEL, related_name="accounts", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(max_digits=10, decimal_places=3)
    tax = models.DecimalField(max_digits=10, decimal_places=3)
    date = models.DateField()
    purchaser = models.ForeignKey(
        USER_MODEL, related_name="receipts", on_delete=models.CASCADE
    )
    category = models.ForeignKey(
        ExpenseCategory, related_name="receipts", on_delete=models.CASCADE
    )
    account = models.ForeignKey(
        Account, related_name="receipts", on_delete=models.CASCADE, null=True
    )

accounts/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login

# Create your views here.


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password1")
            user = User.objects.create_user(
                username=username,
                password=password,
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm(request.POST)

    context = {
        "form": form,
    }
    return render(request, "registration/signup.html", context)

receipts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from receipts.models import Account, ExpenseCategory, Receipt


# # Create your views here.
class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = "receipts/list.html"

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)


class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    template_name = "receipts/create.html"
    fields = ["vendor", "total", "tax", "date", "category", "account"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.purchaser = self.request.user
        item.save()
        return redirect("home")

        ## need purchaser


class AccountsListView(LoginRequiredMixin, ListView):
    model = Account
    template_name = "accounts/list.html"

    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)


class AccountsCreateView(LoginRequiredMixin, CreateView):
    model = Account
    template_name = "accounts/create.html"
    fields = ["name", "number"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("accounts_view")

        ## need owner


class CategoriesListView(LoginRequiredMixin, ListView):
    model = ExpenseCategory
    template_name = "categories/list.html"

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)


class CategoriesCreateView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    template_name = "categories/create.html"
    fields = ["name"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("expense_list")

        ## need owner

accounts/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <title>Expenses
    </title>
</head>

<body>

    <header> 
        <nav>
            {%if user.is_authenticated %}
            <a href="{%url 'home'%}">Home</a>
            <a href="{% url 'accounts_view'%}">Accounts</a>
            <a href="{% url 'expense_list'%}">Expenses</a>

            <a href="{% url 'logout'%}">Logout</a>
            {%else %}
            <a href="{%url 'signup'%}">Sign Up</a>
            <a href="{%url 'login'%}">Login</a>
            {%endif%}
        </nav>
    </header>
<main>
    {% block content%}
    {% endblock content%}
</main>

</body>

</html>

receipts/templates/accounts/create.html
{%extends "base.html"%}

{%block content%}
<h1> Create A New Expense Account</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type='submit'>Create</button>
</form>

{%endblock content%}

receipts/templates/accounts/list.html
{%extends 'base.html'%}

<body>
    {%block content%} 
     <table>
         <thead>
             <tr>
                 <th>Name</th>
                 <th>Number</th>
                 <th>Number of Receipts</th>
             </tr>
         </thead>
         <tbody>
             {%for y in account_list%}
             <tr>
                 <td> {{y.name}} </td>
                 <td> {{y.number}}</td>
                 <td> {{y.receipts.all|length}}</td>
            </tr>
            {%endfor%}
         </tbody>
     </table>
     <main>
         <a href="{%url 'accounts_create'%}"><button>Create New Account</button></a>
     </main>
    {%endblock content%}
</body>

receipts/templates/categories/create.html
{%extends "base.html"%}

{%block content%}
<h1> Create A New Expense Category</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type='submit'>Create</button>
</form>

{%endblock content%}

receipts/templates/categories/list.html
{%extends 'base.html'%}

{%block content%}
<main>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Number of Receipts</th>
            </tr>
        </thead>
        <tbody>
            {% comment %} 'expensecategory' refers to category in your VIEWS >> _list is default from django unless specified with context_obj name {% endcomment %}
            {%for cate in expensecategory_list%} 
            <tr>
                {% comment %} use var 'cat' and refer to property >> 'name' in MODELS {% endcomment %}
                <td> {{ cate.name }} </td>
                {% comment %} use var related_name from FK 'receipts' >> .all is built in method  {% endcomment %}
                <td> {{ cate.receipts.all|length}}</td>
            </tr>

            {%endfor%}
        </tbody>

    </table>
    <body>
        <a href="{%url 'expense_create'%}"> <button>Create New Expense</button></a>
    </body>
</main>
{%endblock content%}

receipts/templates/receipts/create.html
{%extends "base.html"%}

{%block content%}
<h1> Create A New Expense Account</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type='submit'>Create</button>
</form>

{%endblock content%}

receipts/templates/receipts/list.html
{%extends 'base.html'%}
{% comment %} <!doctype html>
<html lang="en">

<head>
    <title>
        Expenses
    </title>
</head> {% endcomment %}

<body>
    {%block content%} 
    <h1>Home</h1>
    <table>
        <thead>
            <tr>
                <th>Vendor</th>
                <th>Total</th>
                <th>Tax</th>
                <th>Date</th>
                <th>Category</th>
                <th>Account</th>
            </tr>
        </thead>
        <tbody>
            {%for i in receipt_list%}
            <tr>  
                <td> {{i.vendor}} </td>
                <td>{{i.total}}</td>
                <td>{{i.tax}}</td>
                <td>{{i.date}}</td>
                <td>{{i.category}}</td>
                {%if i.account == None%}
                <td>Cash</td>
                {%else%}
                <td>{{i.account}}</td>
                {%endif%}
            </tr>
            {%endfor%}
        </tbody>
    </table>
    <main>
        <a href="{%url 'receipt_create'%}"><button>Add New Receipt</button></a>
    </main>
    {%endblock content%}
</body>

{% comment %} </html> {% endcomment %}